Bump rustls-webpki from 0.100.1 to 0.100.3 (#5)
Bumps [rustls-webpki](https://github.com/rustls/webpki) from 0.100.1 to
0.100.3.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rustls/webpki/releases">rustls-webpki's
releases</a>.</em></p>
<blockquote>
<h2>0.100.3</h2>
<ul>
<li>Path building complexity is now limited to a maximum budget of path
finding operations, avoiding exponential processing time when
encountering certificate chains containing many certificates with the
same subject/issuer distinguished name but different subject public key
information.</li>
<li>Name constraints evaluation is now limited to a maximum number of
comparison operations, avoiding exponential processing time when
encountering certificate chains containing many name constraints and
subject alternate names.</li>
</ul>
<h2>What's Changed</h2>
<p>The following PRs were backported to the rel-0.100 branch in <a
href="https://redirect.github.com/rustls/webpki/pull/172">rustls/webpki#172</a></p>
<ul>
<li>Further limits on expensive path building (<a
href="https://redirect.github.com/rustls/webpki/pull/163">rustls/webpki#163</a>)</li>
<li>Budget tweaks (<a
href="https://redirect.github.com/rustls/webpki/pull/164">rustls/webpki#164</a>)</li>
<li>Bound name constraint comparisons (<a
href="https://redirect.github.com/rustls/webpki/pull/165">rustls/webpki#165</a>)</li>
<li>Correct handling of fatal errors (<a
href="https://redirect.github.com/rustls/webpki/pull/168">rustls/webpki#168</a>)</li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/rustls/webpki/compare/v/0.100.2...v/0.100.3">https://github.com/rustls/webpki/compare/v/0.100.2...v/0.100.3</a></p>
<p>Thanks to all who have contributed, on behalf of the rustls team (<a
href="https://github.com/ctz"><code>@​ctz</code></a>, <a
href="https://github.com/cpu"><code>@​cpu</code></a> and <a
href="https://github.com/djc"><code>@​djc</code></a>)!</p>
<h2>v/0.100.2</h2>
<h2>Release notes</h2>
<ul>
<li>certificate path building and verification is now capped at 100
signature validation operations to avoid the risk of CPU usage
denial-of-service attack when validating crafted certificate chains
producing quadratic runtime. This risk affected both clients, as well as
servers that verified client certificates.</li>
</ul>
<h2>What's Changed</h2>
<ul>
<li>v0.100.2 prep by <a
href="https://github.com/cpu"><code>@​cpu</code></a> in <a
href="https://redirect.github.com/rustls/webpki/pull/154">rustls/webpki#154</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/rustls/webpki/compare/v/0.100.1...v/0.100.2">https://github.com/rustls/webpki/compare/v/0.100.1...v/0.100.2</a></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rustls/webpki/commit/5649c6a65073a0b2320bb5337d603b22426dbd4e"><code>5649c6a</code></a>
Cargo: bump version 0.100.2 -&gt; 0.100.3.</li>
<li><a
href="https://github.com/rustls/webpki/commit/86f4cb29749d88eaf6d80d7f185e1c62b1354ebc"><code>86f4cb2</code></a>
verify_cert: use enum for build chain error</li>
<li><a
href="https://github.com/rustls/webpki/commit/50a293091c1e4c1b1cab8c147fbb0981671f971b"><code>50a2930</code></a>
verify_cert: correct handling of fatal errors</li>
<li><a
href="https://github.com/rustls/webpki/commit/0651f72569f9f207acfc66091a83922fd032be5f"><code>0651f72</code></a>
error: add is_fatal helper, use in verify_cert</li>
<li><a
href="https://github.com/rustls/webpki/commit/0598dd29f86d65ea79211744341e0176099192ef"><code>0598dd2</code></a>
verify_cert: optional <code>Budget</code> arg for
<code>verify_chain</code> helper</li>
<li><a
href="https://github.com/rustls/webpki/commit/277fb4be2bb4af71ff8ef814936aeeb6079e777f"><code>277fb4b</code></a>
verify_cert: take references in verify_chain helper</li>
<li><a
href="https://github.com/rustls/webpki/commit/63f78e052eac57d6a91e7c6401a76e276934f4eb"><code>63f78e0</code></a>
verify_cert: name constraint checking on verified chain</li>
<li><a
href="https://github.com/rustls/webpki/commit/f55622a54befabaf3c994a71b987adb4d3ace3ca"><code>f55622a</code></a>
verify_cert: budget for name constraint comparisons</li>
<li><a
href="https://github.com/rustls/webpki/commit/141ddcb13dcf42d18e1c3ce8eb8855b133713f84"><code>141ddcb</code></a>
verify_cert: pull out <code>verify_chain</code> test helper</li>
<li><a
href="https://github.com/rustls/webpki/commit/eb07f2f679e7073d359c465dcb09088b2eee271b"><code>eb07f2f</code></a>
verify_cert: pull out <code>make_end_entity</code> test helper</li>
<li>Additional commits viewable in <a
href="https://github.com/rustls/webpki/compare/v/0.100.1...v/0.100.3">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=rustls-webpki&package-manager=cargo&previous-version=0.100.1&new-version=0.100.3)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)
You can disable automated security fix PRs for this repo from the
[Security Alerts
page](https://github.com/JarredAllen/chess/network/alerts).

</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>